### ISSUE TITLE
Question regarding status of project

### ISSUE THREAD

**Issue by tripodsan** [backflip/htl-loader#1]
Hi @backflip,

I wonder that the status is of this project. I help with the AEM support for [storybook](https://github.com/storybookjs/aem) and need a bit a different behaviour of the htl-loader.
so far, I just hacked what I need [here](https://github.com/storybookjs/aem/blob/master/htl-loader/src/index.js) but would like to contribute changes back to this project.

I would start adding pull-requests with improvement suggestions :-)
WDYT?

**Comment by backflip** [comment]
@tripodsan, sounds great, looking forward to it.

**Comment by tripodsan** [comment]
cool.
